data_path: C:\Users\Eduar\Documents\masters\cap5415\datasets\solar_panel_data\processed\dataset_info.yaml
experiment_info:
  batch_size: 16
  dataset: original_solar
  date: '2024-12-04 19:25:36'
  epochs: 100
  img_size: 640
  model: yolov8s
run_directory: C:\Users\Eduar\Documents\masters\cap5415\solar_project\scripts\yolo_experiments\v8\runs\original_solar\yolov8s_batch16_epoch100_20241204_192536
