data_path: C:\Users\Eduar\Documents\masters\cap5415\datasets\combined_solar_dataset\dataset_info.yaml
experiment_info:
  batch_size: 32
  dataset: combined_solar
  date: '2024-12-04 13:24:46'
  epochs: 100
  img_size: 640
  model: yolov5n
run_directory: C:\Users\Eduar\Documents\masters\cap5415\solar_project\scripts\yolo_experiments\v5\runs\combined_solar\yolov5n_batch32_epoch100_20241204_132446
