batch: 32
box: 7.5
cache: disk
cls: 0.5
data: C:\Users\Eduar\Documents\masters\cap5415\solar_project\scripts\solar_panel_data\processed\dataset.yaml
degrees: 0.0
device: cuda
dfl: 1.5
epochs: 100
exist_ok: true
fliplr: 0.5
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
imgsz: 640
lr0: 0.01
lrf: 0.01
momentum: 0.937
mosaic: 1.0
name: solar_defect_detection_yolov8n_batch32_epoch100_20241110_222741
optimizer: SGD
project: C:\Users\Eduar\Documents\masters\cap5415\solar_project\scripts\runs
save: true
save_period: 10
scale: 0.5
seed: 42
translate: 0.1
verbose: true
warmup_bias_lr: 0.1
warmup_epochs: 3.0
warmup_momentum: 0.8
weight_decay: 0.0005
workers: 8
